name: MetaversePlugin
version: '0-DEV'
main: net.metaversePlugin.MetaversePlugin
api-version: '1.21.4'
load: POSTWORLD
authors: [ RocraftYT ]

commands:
  Ability:
    description: contains all commands related to the abilities.
    usage: /Ability <args>
  Trust:
    description: all commands related to trusting players.
    usage: /Trust <args>
  Item:
    description: all commands related to items.
    usage: /Item <args>
  Dimension:
    description: all commands related to dimensions.
    usage: /Dimension <args>